package pro.chenggang.example.reactive.mybatis.r2dbc.mapper;

import org.apache.ibatis.annotations.Mapper;
import pro.chenggang.example.reactive.mybatis.r2dbc.entity.extend.DeptWithEmp;
import pro.chenggang.example.reactive.mybatis.r2dbc.entity.model.Dept;
import pro.chenggang.example.reactive.mybatis.r2dbc.mapper.dynamic.DeptDynamicMapper;
import reactor.core.publisher.Flux;
import reactor.core.publisher.Mono;

import java.time.LocalDateTime;

/**
 * auto generated
 * @author autoGenerated
 */
@Mapper
public interface DeptMapper extends DeptDynamicMapper {

    Mono<Long> countAll();

    Flux<Dept> selectAll();

    Mono<Dept> selectOneByDeptNo(Long deptNo);

    Flux<Dept> selectListByTime(LocalDateTime createTime);

    Mono<Integer> insertOne(Dept dept);

    Mono<Integer> deleteByDeptNo(Long deptNo);

    Mono<Integer> updateByDeptNo(Dept dept);

    Flux<DeptWithEmp> selectDeptWithEmpList();
}