package pro.chenggang.example.reactive.mybatis.r2dbc.mapper;

import org.apache.ibatis.annotations.Mapper;
import pro.chenggang.example.reactive.mybatis.r2dbc.entity.extend.EmpWithDept;
import pro.chenggang.example.reactive.mybatis.r2dbc.entity.model.Emp;
import pro.chenggang.example.reactive.mybatis.r2dbc.mapper.dynamic.EmpDynamicMapper;
import reactor.core.publisher.Flux;

/**
 * auto generated
 * @author autoGenerated
 */
@Mapper
public interface EmpMapper extends EmpDynamicMapper {

    Flux<EmpWithDept> selectEmpWithDeptList();

    Flux<Emp> selectByParameterMap(Emp emp);
}