server:
  port: 9999
  netty:
    connection-timeout: PT120S
r2dbc:
  mybatis:
    mapper-locations: classpath:mapper/*.xml
    configuration-properties:
      map-underscore-to-camel-case: true
spring:
  r2dbc:
    mybatis:
      r2dbc-url: r2dbc:h2:file:///./database/r2dbc?options=MODE=MySQL;AUTO_RECONNECT=TRUE;DB_CLOSE_DELAY=-1;DATABASE_TO_LOWER=TRUE;DB_CLOSE_ON_EXIT=FALSE
      username: root
      password: 123456
      pool:
        max-idle-time: PT3M
        validation-query: SELECT 1 FROM DUAL
        initial-size: 1
        max-size: 3
        acquire-retry: 3
        validation-depth: REMOTE
        max-create-connection-time: PT30S
logging:
  level:
    pro.chenggang: DEBUG
    org.springframework.r2dbc: DEBUG
    io.r2dbc: INFO
  file:
    path: ./logs