server:
  port: 9999
  netty:
    connection-timeout: PT120S
r2dbc:
  mybatis:
    mapper-locations: classpath:mapper/*.xml
    configuration-properties:
      map-underscore-to-camel-case: true
spring:
  r2dbc:
    mybatis:
      r2dbc-url: r2dbc:mssql://127.0.0.1:1433/r2dbc
      username: SA
      password: Abcd@1234
      pool:
        max-idle-time: PT3M
        validation-query: SELECT 1
        initial-size: 1
        max-size: 3
        acquire-retry: 3
        validation-depth: REMOTE
        max-create-connection-time: PT30S
logging:
  level:
    pro.chenggang: DEBUG
    org.springframework.r2dbc: DEBUG
    io.r2dbc: INFO
  file:
    path: ./logs